kind: Service
apiVersion: v1
metadata:
  name: example
  namespace: example
spec:
    selector:
        app: example
    type: ClusterIP
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80