apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 31a9eb2a-3b32-4ab4-9e8e-896d90602535
  labels:
    azure.workload.identity/use: "true"
  name: example-sa
  namespace: example